[package]
name = "ensemblcov"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rayon = "1.10.0"
tokio = { version = "1.45.1", features = ["full", "io-util", "tokio-macros"] }
